### ISSUE TITLE
Error Importing module named app

### ISSUE THREAD

**Issue by theparadoxer02** [cldrn/rainmap-lite#10]
while deploying on my local server on django 1.9.6
the following error came-

```
  File "/home/cyborg/Desktop/cyber/rainmap-lite/rainmap-lite/nmaper/apps.py", line 3, in <module>
    from django.apps import AppConfig
    from django.apps import AppConfig

```

**Comment by lightos** [comment]
I just tried installing on Kali 2.0 using Django 1.9.8 and wasn't able to replicate this error. What is the exact error? What are the steps to replicate? At what stage during the deployment does this happen? Thanks!

**Comment by theparadoxer02** [comment]
I followed all steps ,making a virtual environment and then after installing the django and lxml,After this cloning the repo and then when i migrated to manage.py and then run the command manage.py runserver,it showed the above error in the terminal!.

**Comment by theparadoxer02** [comment]
Also i think the wiki should be updated! and added some more detail about the installation and making docs for deploying in virtual environment.
Thanks!

**Comment by cldrn** [comment]
I haven't deployed it with virtualenv yet but I will try it and update the wiki accordingly. Cheers.

**Comment by cldrn** [comment]
Are you referencing your virtual environment's python binary correctly? I tried to replicate the error using django 1.10.2 with virtualenv and I couldn't produce the error message.

I created a new wiki page with instructions for [running rainmap-lite with virtualenv](https://github.com/cldrn/rainmap-lite/wiki/INSTALL-in-Virtual-Environment)

**Comment by cldrn** [comment]
I'm closing this issue and we never were able to replicate it. Feel free to open it again with more details.
