### ISSUE TITLE
Console page

### ISSUE THREAD

**Issue by Duartebm** [cldrn/rainmap-lite#11]
Neither /console/ nor the /domador/ page you showed in the video work at all.
While the /domador/ page seems not to be recognized at all, the /console/ one actually tries something and takes a while to load, and shows a lot of information after it open.
This is the page I get when I try to open it the /console/ page:

[RuntimeError at _console_.html.zip](https://github.com/cldrn/rainmap-lite/files/614490/RuntimeError.at._console_.html.zip)

**Comment by Duartebm** [comment]
I've been trying to understand the error, and this is what I understood: /rainmap-lite/nmaper/templates/admin/index.html is trying to call itself in the first line of code, by saying "{% extends "admin/index.html" %}"
To fix that, I replaced that line with "{% extends "admin/base_site.html" %}" instead, and now I got something:
![rainmap](https://cloud.githubusercontent.com/assets/10181038/20669252/1a05319c-b56b-11e6-9a85-ba6592ea9476.png)

Even though I now have some kind of page, it is not completed. As you can see in the picture, it's missing the administration options.

Please help fixing this, I've really tried...

**Comment by Duartebm** [comment]
I just scrolled to the side and found this:
![rainmap2](https://cloud.githubusercontent.com/assets/10181038/20669354/a9ca767a-b56b-11e6-8ede-b8bec1405cde.png)

It's obviously not supposed to be there and it gives me no more options than clearing the logs, but I guess it's some kind of progress?

**Comment by cldrn** [comment]
Hello,

Thank you for the bug report. I see that you're running Django 1.8. The supported version are 1.9.x and 1.10.x. While it may work on 1.8, we haven't tested it. Can you update your Django version and try again?

Cheers.

**Comment by cldrn** [comment]
You may install the supported django version with virtualenv if you don't want to update at system level:
[https://github.com/cldrn/rainmap-lite/wiki/INSTALL-in-Virtual-Environment](https://github.com/cldrn/rainmap-lite/wiki/INSTALL-in-Virtual-Environment)

**Comment by Duartebm** [comment]
Sorry for the time I took to respound, I've been busy over here.
I upgraded Django to version 1.10, and the console page looks exacly the same... Actually, the only thing I got from upgrading was a big BIG problem! Now I have to put the "Allowed Hosts" in the settings.py ...

**Comment by cldrn** [comment]
Was that a clean installation? Can you share more details about your environment? 
I certainly didn't have to add anything to Allowed Hosts when I tested on Django 1.10.x.

**Comment by Duartebm** [comment]
I'm trying to use this on Kali Linux, and all I did was update Django to the 1.10.x version using pip and it added the Allowed Host option...

**Comment by cldrn** [comment]
Hello,

I just posted a video going over the installation process: [Install Rainmap Lite](https://www.youtube.com/watch?v=RsOd4uRtfTc&feature=youtu.be)

Hope this helps you install the application.
