### ISSUE TITLE
Error deploying it on django 1.9

### ISSUE THREAD

**Issue by theparadoxer02** [cldrn/rainmap-lite#9]
_In template /home/cyborg/Desktop/raimap-lite/rainmap-lite/rainmap-lite/nmaper/templates/registration/login.html, error at line 44_

**Reverse for '' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []**
The error is coming on the line (tried to debug it but was unable to do )-

`<form action="{% url 'django.contrib.auth.views.login' %}" method="post" id="login-form">{% csrf_token %}`

**Comment by lightos** [comment]
Fixed in commit https://github.com/cldrn/rainmap-lite/commit/6d343644ebc8d60025318edc96edd413470e33b7
